[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "vite"
  port = 8888
  targetPort = 5173
  publish = "dist"
  framework = "#custom"

# Ensure environment variables are passed to functions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

# Add CORS headers for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" 